### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by pike2k** [jonasbystrom/ESP-Now-Sensor-system-with-WiFi#1]
I see references to existing code, but I see no code in Repo?

**Comment by jonasbystrom** [comment]
True and sorry.
I never had the time to make the code "public" and release it. As I would need to remove lots of other stuff and simplify just the needed code.
If you tell what is mostly wanted I could - hopefully - publish during my Christmas vacation ...

// Btw, I was just sitting down here to view a graph of a D1 Mini Pro with a DS18B20 temp sensor and a 1200mAh battery. It has now been running for 13+ months and is "about to die". All on standard unmodified HW.

**Comment by jonasbystrom** [comment]
This is now fixed. I have uploaded ESP8266 code for sensor and gateway. 
This is all needed for a working system with ESP8266. I will later update with ESP32 additions.

**Comment by jonasbystrom** [comment]
Code updated.Closed.
